$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

# Windows PowerShell 5.1 defines neither, and only ever runs on Windows. See llmfit.ps1.
$onWindows = if ($null -ne $IsWindows) { [bool]$IsWindows } else { $true }

if ($onWindows) {
  # The 'User' environment target is the Windows registry. There is no such
  # thing on macOS, which is why the two halves of this script share nothing.
  $required = @(
    (Join-Path $root 'bin'),
    (Join-Path $root (Join-Path 'tools' 'node')),
    (Join-Path $root (Join-Path 'tools' (Join-Path 'pi' (Join-Path 'node_modules' '.bin'))))
  )
  $current = [Environment]::GetEnvironmentVariable('Path', 'User')
  $entries = @($current -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
  foreach ($entry in $required) {
    if ($entries -notcontains $entry) { $entries += $entry }
  }
  [Environment]::SetEnvironmentVariable('Path', ($entries -join ';'), 'User')
  foreach ($entry in $required) { Write-Host "PATH: $entry" -ForegroundColor DarkGray }
  Write-Host ''
  Write-Host 'Installed for the current user.' -ForegroundColor Green
  Write-Host 'Open a new terminal and run: llmfit' -ForegroundColor Cyan
  Write-Host 'You can also use START.cmd without touching PATH.'
  exit 0
}

# ------------------------------------------------------------------- macOS

# Only bin/ goes on the PATH here. tools/node and tools/pi are runtimes a
# Windows package vendors so an offline machine can still run Pi; on macOS Pi
# is an npm install like any other tool and is already wherever npm put it.
$binDirectory = Join-Path $root 'bin'

$shell = if ($env:SHELL) { Split-Path -Leaf $env:SHELL } else { 'zsh' }
$profilePath = switch ($shell) {
  'zsh' { Join-Path $HOME '.zshrc' }
  'bash' { Join-Path $HOME '.bash_profile' }
  default { $null }
}
if (-not $profilePath) {
  Write-Host "Unrecognised shell: $shell" -ForegroundColor Yellow
  Write-Host 'Add this to your shell profile by hand:' -ForegroundColor Yellow
  # ${} is required: PowerShell reads "$binDirectory:" as a scoped variable
  # reference, the same syntax as $env:PATH, and refuses to parse the file.
  Write-Host "  export PATH=`"${binDirectory}:`$PATH`""
  exit 1
}

$begin = '# >>> llmfit BEGIN (generated by install-path.ps1; do not edit by hand)'
$end = '# <<< llmfit END'
$block = "$begin`nexport PATH=`"${binDirectory}:`$PATH`"`n$end`n"

$body = ''
if (Test-Path -LiteralPath $profilePath) {
  # Same rule the harness configuration follows: back the file up once, before
  # the first write, and never touch anything outside the managed block.
  $backup = "$profilePath.llmfit-backup"
  if (-not (Test-Path -LiteralPath $backup)) {
    Copy-Item -LiteralPath $profilePath -Destination $backup -Force
    Write-Host "  backup saved: $backup" -ForegroundColor DarkGray
  }
  $pattern = [regex]::Escape($begin) + '.*?' + [regex]::Escape($end)
  $body = ([regex]::Replace((Get-Content -Raw -LiteralPath $profilePath), $pattern, '', [System.Text.RegularExpressions.RegexOptions]::Singleline)).TrimEnd()
}

$content = if ([string]::IsNullOrWhiteSpace($body)) { $block } else { "$body`n`n$block" }
[System.IO.File]::WriteAllText($profilePath, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "PATH: $binDirectory" -ForegroundColor DarkGray
Write-Host "  written to: $profilePath" -ForegroundColor DarkGray
Write-Host ''
Write-Host 'Installed for the current user.' -ForegroundColor Green
Write-Host 'Open a new terminal and run: llmfit' -ForegroundColor Cyan
Write-Host 'You can also use START.command without touching PATH.'
